cd /home/ziyang/Pmem/filebench
for f in fileserver_wl_pmfs.f fileserver_wl_pmfs1.f fileserver_wl1.f fileserver_wl.f
do
	sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect hotspots -knob sampling-interval=10 -knob enable-user-tasks=false -knob enable-gpu-usage=false -knob enable-gpu-runtimes=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f} > ${f}.hotspots.log

	sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect advanced-hotspots -knob sampling-interval=1 -knob collection-detail=stack-call-and-tripcount -knob event-mode=all -knob enable-user-tasks=true -knob enable-gpu-usage=false -knob enable-gpu-runtimes=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f} > ${f}.advanced.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect concurrency -knob sampling-interval=10 -knob enable-user-tasks=true -knob enable-user-sync=true -knob enable-gpu-usage=true -knob enable-gpu-runtimes=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.concurrency.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect locksandwaits -knob sampling-interval=10 -knob enable-user-tasks=true -knob enable-user-sync=true -knob enable-gpu-usage=true -knob enable-gpu-runtimes=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.locksandwaits.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=false -knob collect-memory-bandwidth=true -knob enable-user-tasks=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.memory-bandwidth.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=true -knob collect-memory-bandwidth=false -knob enable-user-tasks=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.stack-collection.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=false -knob collect-memory-bandwidth=false -knob enable-user-tasks=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.user-tasks.log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect bandwidth -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/filebench -- /home/ziyang/Pmem/filebench/filebench  -f /home/ziyang/Pmem/filebench/${f}  > ${f}.bandwidth.log
done


cd /home/ziyang/Pmem/redis-3.0.1
f= redisCluster
#	sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect hotspots -knob sampling-interval=10 -knob enable-user-tasks=true -knob enable-gpu-usage=false -knob enable-gpu-runtimes=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.hotspots_log
#	sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect hotspots -knob sampling-interval=10 -knob enable-user-tasks=false -knob enable-gpu-usage=false -knob enable-gpu-runtimes=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.hotspots_log

	sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect advanced-hotspots -knob sampling-interval=1 -knob collection-detail=stack-call-and-tripcount -knob event-mode=all -knob enable-user-tasks=true -knob enable-gpu-usage=false -knob enable-gpu-runtimes=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.advanced_log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect concurrency -knob sampling-interval=10 -knob enable-user-tasks=true -knob enable-user-sync=true -knob enable-gpu-usage=true -knob enable-gpu-runtimes=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.concurrency_log
	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect locksandwaits -knob sampling-interval=10 -knob enable-user-tasks=true -knob enable-user-sync=true -knob enable-gpu-usage=true -knob enable-gpu-runtimes=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.locksandwaits_log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=false -knob collect-memory-bandwidth=true -knob enable-user-tasks=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.bandwidth_log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=true -knob collect-memory-bandwidth=false -knob enable-user-tasks=false -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.memory-bandwidth_log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect general-exploration -knob enable-stack-collection=false -knob collect-memory-bandwidth=false -knob enable-user-tasks=true -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.user-tasks_log

	 sudo /opt/intel/vtune_amplifier_xe_2015.3.0.403110/bin64/amplxe-cl -collect bandwidth -follow-child -mrte-mode=auto -target-duration-type=short -no-allow-multiple-runs -no-analyze-system -data-limit=500 -slow-frames-threshold=40 -fast-frames-threshold=100 -no-analyze-kvm-guest -app-working-dir /home/ziyang/Pmem/redis-3.0.1 -- /home/ziyang/Pmem/redis-3.0.1/runtest-cluster > ${f}.bandwidth_log


